### ISSUE TITLE
Proposal to Refactor Inline Styles with Tailwind CSS

### ISSUE THREAD

**Issue by DevitoDbug** [MuchiriAndrew/blubox-logistics#1]
I think i should re-write tailwind for the inline styles you have used. I'll be happy to refactor the code.

**Comment by MuchiriAndrew** [comment]
> I think i should re-write tailwind for the inline styles you have used. I'll be happy to refactor the code.

Thanks a lot for the offer. But I'm afraid this project is one I'm doing for my workplace and the codebase will be used by others who might not be familiar with tailwind and to be honest I prefer using actual CSS or sass for my styling.
For now I'm actually getting most of the code from the UI/UX designs in figma but I eventually plan on transferring all the inline styles to css files where I'll also use media queries to make the site responsive.
Thanks again.

**Comment by DevitoDbug** [comment]
nice ... i also like inlines. Tailwind is like inline on steroids. Have fun though👍
